from __future__ import annotations

import re
import uuid
from pathlib import Path
from typing import Any

from docx import Document
from pptx import Presentation
from pptx.util import Inches, Pt
from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


BASE_DIR = Path(__file__).resolve().parents[1]
EXPORT_DIR = BASE_DIR / "exports"
EXPORT_DIR.mkdir(exist_ok=True)


def create_export(export_type: str, payload: dict[str, Any]) -> Path:
    title = payload.get("title") or "AI Workspace Document"
    blocks = payload.get("blocks")
    if not isinstance(blocks, list):
        raise ValueError("Document payload must include a blocks array.")

    filename = f"{_slug(title)}-{uuid.uuid4().hex[:8]}.{export_type}"
    path = EXPORT_DIR / filename

    if export_type == "pdf":
        _write_pdf(path, title, blocks)
    elif export_type == "docx":
        _write_docx(path, title, blocks)
    elif export_type == "pptx":
        _write_pptx(path, title, blocks)
    else:
        raise ValueError("Unsupported export type.")

    return path


def _slug(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", value.lower()).strip("-")
    return slug or "document"


def _block_text(block: dict[str, Any]) -> str:
    if "content" in block:
        return str(block["content"])
    if "items" in block and isinstance(block["items"], list):
        return "\n".join(f"- {item}" for item in block["items"])
    if block.get("type") == "chart":
        labels = ", ".join(map(str, block.get("labels", [])))
        data = ", ".join(map(str, block.get("data", [])))
        return f"{block.get('chartType', 'bar').title()} chart: {labels} ({data})"
    if block.get("type") == "image":
        return f"Image prompt: {block.get('prompt', '')}"
    return str(block.get("subtitle") or block.get("caption") or "")


def _write_pdf(path: Path, title: str, blocks: list[dict[str, Any]]) -> None:
    doc = SimpleDocTemplate(str(path), pagesize=LETTER, rightMargin=42, leftMargin=42, topMargin=46, bottomMargin=46)
    styles = getSampleStyleSheet()
    story = [Paragraph(title, styles["Title"]), Spacer(1, 18)]

    for block in blocks:
        heading = block.get("heading") or block.get("title") or block.get("label") or block.get("type", "Section").title()
        story.append(Paragraph(str(heading), styles["Heading2"]))
        if block.get("type") == "stat":
            table = Table([[block.get("value", ""), block.get("caption", "")]], colWidths=[110, 350])
            table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#111827")),
                        ("TEXTCOLOR", (0, 0), (-1, -1), colors.white),
                        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#7c3aed")),
                        ("PADDING", (0, 0), (-1, -1), 12),
                    ]
                )
            )
            story.append(table)
        else:
            story.append(Paragraph(_block_text(block).replace("\n", "<br/>"), styles["BodyText"]))
        story.append(Spacer(1, 12))

    doc.build(story)


def _write_docx(path: Path, title: str, blocks: list[dict[str, Any]]) -> None:
    doc = Document()
    doc.add_heading(title, level=0)

    for block in blocks:
        heading = block.get("heading") or block.get("title") or block.get("label") or block.get("type", "Section").title()
        doc.add_heading(str(heading), level=1)
        if block.get("type") == "bullets" or block.get("type") == "summary":
            for item in block.get("items", []):
                doc.add_paragraph(str(item), style="List Bullet")
        else:
            doc.add_paragraph(_block_text(block))

    doc.save(path)


def _write_pptx(path: Path, title: str, blocks: list[dict[str, Any]]) -> None:
    presentation = Presentation()
    title_slide_layout = presentation.slide_layouts[0]
    slide = presentation.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = title
    slide.placeholders[1].text = "Generated by AI Workspace"

    content_layout = presentation.slide_layouts[5]
    for block in blocks[:10]:
        slide = presentation.slides.add_slide(content_layout)
        slide.shapes.title.text = str(block.get("heading") or block.get("title") or block.get("label") or block.get("type", "Section").title())
        box = slide.shapes.add_textbox(Inches(0.8), Inches(1.45), Inches(8.6), Inches(4.5))
        frame = box.text_frame
        frame.word_wrap = True
        paragraph = frame.paragraphs[0]
        paragraph.text = _block_text(block)
        paragraph.font.size = Pt(18)

    presentation.save(path)
